twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/static/css': styles
        '%kernel.project_dir%/public/static/images': images
    form_themes:
        - 'form/theme.html.twig'

when@test:
    twig:
        strict_variables: true
