# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    menu_directory: '%kernel.project_dir%/public/uploads/menu'
    boisson_directory: '%kernel.project_dir%/public/uploads/imgBoisson'
    dessert_directory: '%kernel.project_dir%/public/uploads/imgDessert'
    photoeleve_directory: '%kernel.project_dir%/public/uploads/photoFile'
    sandwich_directory: '%kernel.project_dir%/public/uploads/imgSandwich'
    elevefile_directory: '%kernel.project_dir%/public/uploads/eleveFile'
    adultefile_directory: '%kernel.project_dir%/public/uploads/adulteFile'
    cantineFile_directory: '%kernel.project_dir%/public/uploads/cantineFile'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    app.twig.switch:
        class: buzzingpixel\twigswitch\SwitchTwigExtension
        tags:
            - { name: twig.extension }
    # Make classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
